### ISSUE TITLE
aws-robomaker-hospital-world launch error with ROS1+ Kinetic + catkin package?

### ISSUE THREAD

**Issue by Sivasankar-Ganesan** [jerwallace/aws-robomaker-workshops#14]
Whether aws-robomaker-hospital-world package support with ROS1 and catkin package?

While running roslaunch aws_robomaker_hospital_world hospital.launch command
[Wrn] [ColladaLoader.cc:1404] Unable to add material[]

[Err] [MeshManager.cc:96] Invalid mesh filename extension[/home/xxxxx/catkin_ws/src/aws-robomaker-hospital-world/fuel_models/CGMClassic/meshes/CGMClassic.obj]
[Err] [MeshShape.cc:72] Unable to load mesh from file[/home/xxxxx/catkin_ws/src/aws-robomaker-hospital-world/fuel_models/CGMClassic/meshes/CGMClassic.obj]

Help me to solve this error.

**Comment by jerwallace** [comment]
Hi @Sivasankar-Ganesan - Thanks for your message. That error is due to an incorrect relative link for a mesh in one of the 3D models stored in the Ignition Fuel database. It shouldn't impact the running of the application, but if you want you could remove the references to that model and/or make a small change. 

In the model folder: 
fuel_models/CGMClassic/meshes/

Open CGMClassic.MTL in a text editor, then overwrite the file with this (just adds the ".png" extension to the model):

```
# 3ds Max Wavefront OBJ Exporter v0.97b - (c)2007 guruware
# File Created: 15.05.2018 18:22:24

newmtl CGMClassic
	Ns 10.0000
	Ni 1.5000
	d 1.0000
	Tr 0.0000
	Tf 1.0000 1.0000 1.0000 
	illum 2
	Ka 0.5882 0.5882 0.5882
	Kd 0.5882 0.5882 0.5882
	Ks 0.0000 0.0000 0.0000
	Ke 0.0000 0.0000 0.0000
	map_Ka CGMClassic_Diffuse.png
	map_Kd CGMClassic_Diffuse.png

newmtl Wheels
	Ns 10.0000
	Ni 1.5000
	d 1.0000
	Tr 0.0000
	Tf 1.0000 1.0000 1.0000 
	illum 2
	Ka 0.5882 0.5882 0.5882
	Kd 0.5882 0.5882 0.5882
	Ks 0.0000 0.0000 0.0000
	Ke 0.0000 0.0000 0.0000
	map_Ka Carts_Wheels_Diffuse.png
	map_Kd Carts_Wheels_Diffuse.png
	map_bump Wheels_Normal_Normal_Bump.tga
```
